repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: no-commit-to-branch
        args: [--branch, master]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.11.0"
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "2.5.1"
    hooks:
      - id: pyproject-fmt
